CREATE TABLE BD_RISK_DETAIL_PRODUCTION_PD2 (
ID NUMBER(20) NOT NULL ,
ORG_CODE VARCHAR2(64 CHAR) NOT NULL ,
BATCH_NO VARCHAR2(128 CHAR) NOT NULL ,
WO_TYPE VARCHAR2(64 CHAR) NOT NULL ,
WO_NO VARCHAR2(128 CHAR) NOT NULL ,
TIMECOST NUMBER(20,5) NULL ,
CHECK_TIME DATE NOT NULL ,
ISCURRENT NUMBER(10) NOT NULL ,
LASTUPDATE DATE NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD2.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD2.ORG_CODE IS '经营企业18位信用代码';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD2.BATCH_NO IS '批次号';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD2.WO_TYPE IS '工单类型';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD2.WO_NO IS '工单号';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD2.TIMECOST IS '耗用工时';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD2.CHECK_TIME IS '模型运行时间';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD2.ISCURRENT IS '是否使用：1(使用)；0(不使用)';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD2.LASTUPDATE IS '数据最后更新时间';


-- ----------------------------
-- Indexes structure for table BD_RISK_DETAIL_PRODUCTION_PD2
-- ----------------------------

-- ----------------------------
-- Checks structure for table BD_RISK_DETAIL_PRODUCTION_PD2
-- ----------------------------
ALTER TABLE BD_RISK_DETAIL_PRODUCTION_PD2 ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_FILE
-- ----------------------------
ALTER TABLE BD_RISK_DETAIL_PRODUCTION_PD2 ADD PRIMARY KEY (ID);