CREATE TABLE BD_RISK_DETAIL_PRODUCTION_PD4 (
ID NUMBER(20) NOT NULL ,
ORG_CODE VARCHAR2(64 CHAR) NOT NULL ,
WO_NO VARCHAR2(128 CHAR) NOT NULL ,
RLT_BILL_DETAIL_SEQNO VARCHAR2(128 CHAR) NOT NULL ,
COP_G_NO VARCHAR2(128 CHAR) NOT NULL ,
OUT_TIME DATE NOT NULL,
BACK_TIME DATE NULL,
WO_TIME DATE NULL,
INSTOCK_TIME DATE NULL,
CHECK_TIME DATE NOT NULL,
ISCURRENT NUMBER(10) NOT NULL,
LASTUPDATE DATE NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD4.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD4.ORG_CODE IS '公司社会信用代码';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD4.WO_NO IS '工单号';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD4.RLT_BILL_DETAIL_SEQNO IS '关联单号';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD4.COP_G_NO IS '料号';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD4.OUT_TIME IS '领用时间';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD4.BACK_TIME IS '退库时间';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD4.WO_TIME IS '工单时间';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD4.INSTOCK_TIME IS '产出入库时间';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD4.CHECK_TIME IS '运行时间';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD4.ISCURRENT IS '是否使用';
COMMENT ON COLUMN BD_RISK_DETAIL_PRODUCTION_PD4.LASTUPDATE IS '数据最后更新时间';


-- ----------------------------
-- Indexes structure for table BD_RISK_DETAIL_PRODUCTION_PD4
-- ----------------------------

-- ----------------------------
-- Checks structure for table BD_RISK_DETAIL_PRODUCTION_PD4
-- ----------------------------
ALTER TABLE BD_RISK_DETAIL_PRODUCTION_PD4 ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_FILE
-- ----------------------------
ALTER TABLE BD_RISK_DETAIL_PRODUCTION_PD4 ADD PRIMARY KEY (ID);