CREATE TABLE BD_RISK_GRAPH_CREDIT_CR3 (
ID NUMBER(20) NOT NULL ,
ORG_CODE VARCHAR2(64 CHAR) NOT NULL ,
STA_DATE VARCHAR2(64 CHAR) NOT NULL ,
GOODS_VALUE NUMBER(20,5) ,
GOODS_UNIT VARCHAR2(64 CHAR) ,
CBRS NUMBER(20,5),
CBRS_UNIT VARCHAR2(64 CHAR) ,
ELECTRIC NUMBER(20,5),
ELECTRIC_UNIT VARCHAR2(64 CHAR) ,
CHECK_TIME DATE NOT NULL ,
ISCURRENT NUMBER(10) NOT NULL ,
LASTUPDATE DATE NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_GRAPH_CREDIT_CR3.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_GRAPH_CREDIT_CR3.ORG_CODE IS '经营企业18位信用代码';
COMMENT ON COLUMN BD_RISK_GRAPH_CREDIT_CR3.STA_DATE IS '统计日期';
COMMENT ON COLUMN BD_RISK_GRAPH_CREDIT_CR3.GOODS_VALUE IS '进出口额';
COMMENT ON COLUMN BD_RISK_GRAPH_CREDIT_CR3.GOODS_UNIT IS '进出口额单位';
COMMENT ON COLUMN BD_RISK_GRAPH_CREDIT_CR3.CBRS IS '参保人数';
COMMENT ON COLUMN BD_RISK_GRAPH_CREDIT_CR3.CBRS_UNIT IS '参保人数单位';
COMMENT ON COLUMN BD_RISK_GRAPH_CREDIT_CR3.ELECTRIC IS '用电量';
COMMENT ON COLUMN BD_RISK_GRAPH_CREDIT_CR3.ELECTRIC_UNIT IS '用电量单位';
COMMENT ON COLUMN BD_RISK_GRAPH_CREDIT_CR3.CHECK_TIME IS '模型运行时间';
COMMENT ON COLUMN BD_RISK_GRAPH_CREDIT_CR3.ISCURRENT IS '是否使用：1(使用)；0(不使用)';
COMMENT ON COLUMN BD_RISK_GRAPH_CREDIT_CR3.LASTUPDATE IS '数据最后更新时间';


-- ----------------------------
-- Indexes structure for table BD_RISK_GRAPH_CREDIT_CR3
-- ----------------------------

-- ----------------------------
-- Checks structure for table BD_RISK_GRAPH_CREDIT_CR3
-- ----------------------------
ALTER TABLE BD_RISK_GRAPH_CREDIT_CR3 ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_FILE
-- ----------------------------
ALTER TABLE BD_RISK_GRAPH_CREDIT_CR3 ADD PRIMARY KEY (ID);