CREATE TABLE BD_RISK_DETAIL_STOCK_ST2 (
ID NUMBER(20) NOT NULL ,
ORG_CODE VARCHAR2(64 CHAR) NOT NULL ,
STARTDT DATE NOT NULL ,
ENDDT DATE NOT NULL ,
COP_G_NO VARCHAR2(128 CHAR) NULL ,
QTY_BEFORE NUMBER(20,5) NOT NULL ,
QTY_CHANGE NUMBER(20,5) NOT NULL ,
QTY_AFTER NUMBER(20,5) NOT NULL ,
CHECK_TIME DATE NOT NULL ,
ISCURRENT NUMBER(10) NOT NULL ,
LASTUPDATE DATE NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_DETAIL_STOCK_ST2.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_DETAIL_STOCK_ST2.ORG_CODE IS '经营企业18位信用代码';
COMMENT ON COLUMN BD_RISK_DETAIL_STOCK_ST2.STARTDT IS '期初时间';
COMMENT ON COLUMN BD_RISK_DETAIL_STOCK_ST2.ENDDT IS '期末时间';
COMMENT ON COLUMN BD_RISK_DETAIL_STOCK_ST2.COP_G_NO IS '料号';
COMMENT ON COLUMN BD_RISK_DETAIL_STOCK_ST2.QTY_BEFORE IS '期初库存';
COMMENT ON COLUMN BD_RISK_DETAIL_STOCK_ST2.QTY_CHANGE IS '库存变化量';
COMMENT ON COLUMN BD_RISK_DETAIL_STOCK_ST2.QTY_AFTER IS '期末库存';
COMMENT ON COLUMN BD_RISK_DETAIL_STOCK_ST2.CHECK_TIME IS '模型运行时间';
COMMENT ON COLUMN BD_RISK_DETAIL_STOCK_ST2.ISCURRENT IS '是否使用：1(使用)；0(不使用)';
COMMENT ON COLUMN BD_RISK_DETAIL_STOCK_ST2.LASTUPDATE IS '数据最后更新时间';


-- ----------------------------
-- Indexes structure for table BD_RISK_DETAIL_STOCK_ST2
-- ----------------------------

-- ----------------------------
-- Checks structure for table BD_RISK_DETAIL_STOCK_ST2
-- ----------------------------
ALTER TABLE BD_RISK_DETAIL_STOCK_ST2 ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_FILE
-- ----------------------------
ALTER TABLE BD_RISK_DETAIL_STOCK_ST2 ADD PRIMARY KEY (ID);