CREATE TABLE OPENING_INVENTORY_DETAIL (
ID NUMBER(10) NOT NULL ,
PID NUMBER(10) NOT NULL ,
GDS_MTNO VARCHAR2(32 CHAR) NOT NULL ,
GDS_NM VARCHAR2(768 CHAR) NULL ,
GDECD VARCHAR2(10 CHAR)  NULL ,
DCL_UNITCD VARCHAR2(10 CHAR) NOT NULL ,
CLASSIFY_TYPE VARCHAR2(10 CHAR) NOT NULL ,
DCL_QTY NUMBER(19,5) NOT NULL ,
TRADE_TOTAL NUMBER(25,5) NOT NULL ,
TRADE_CURR VARCHAR2(10 CHAR) NOT NULL ,
WAREHOUSE_NO VARCHAR2(50 CHAR) NOT NULL ,
STORAGE_NO VARCHAR2(50 CHAR) NOT NULL,
ISCURRENT NUMBER(10) NOT NULL,
LASTUPDATE DATE NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;
COMMENT ON COLUMN OPENING_INVENTORY_DETAIL.ID IS 'ID';
COMMENT ON COLUMN OPENING_INVENTORY_DETAIL.PID IS 'PID';
COMMENT ON COLUMN OPENING_INVENTORY_DETAIL.GDS_MTNO IS '料号';
COMMENT ON COLUMN OPENING_INVENTORY_DETAIL.GDS_NM IS '商品名称';
COMMENT ON COLUMN OPENING_INVENTORY_DETAIL.GDECD IS '商品编码HS_CODE';
COMMENT ON COLUMN OPENING_INVENTORY_DETAIL.DCL_UNITCD IS '计量单位';
COMMENT ON COLUMN OPENING_INVENTORY_DETAIL.CLASSIFY_TYPE IS '料件成品标志 I-料件,E-成品,S-设备,L-边角料,D-残次品,F-待维修件,G-已维修件,H-维修边角料,J-维修坏件,B-半成品';
COMMENT ON COLUMN OPENING_INVENTORY_DETAIL.DCL_QTY IS '数量';
COMMENT ON COLUMN OPENING_INVENTORY_DETAIL.TRADE_TOTAL IS '总价';
COMMENT ON COLUMN OPENING_INVENTORY_DETAIL.TRADE_CURR IS '币制 见码表';
COMMENT ON COLUMN OPENING_INVENTORY_DETAIL.WAREHOUSE_NO IS '仓库号';
COMMENT ON COLUMN OPENING_INVENTORY_DETAIL.STORAGE_NO IS '库位号';
COMMENT ON COLUMN OPENING_INVENTORY_DETAIL.ISCURRENT IS '是否有效';
COMMENT ON COLUMN OPENING_INVENTORY_DETAIL.LASTUPDATE IS '最后更新时间';

ALTER TABLE OPENING_INVENTORY_DETAIL ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table OPENING_INVENTORY_DETAIL
-- ----------------------------
ALTER TABLE OPENING_INVENTORY_DETAIL ADD PRIMARY KEY (ID);