CREATE TABLE OPENING_INVENTORY (
ID NUMBER(10) NOT NULL ,
TRADE_CODE VARCHAR2(10 CHAR) NOT NULL ,
TRADE_NAME VARCHAR2(64 CHAR) NOT NULL ,
CREDIT_CODE VARCHAR2(64 CHAR) NOT NULL ,
OPT_DATE DATE NOT NULL,
CREATE_TIME DATE NOT NULL,
ISCURRENT NUMBER(10) NOT NULL,
LASTUPDATE DATE NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN OPENING_INVENTORY.ID IS 'ID';
COMMENT ON COLUMN OPENING_INVENTORY.TRADE_CODE IS '企业十位数编码';
COMMENT ON COLUMN OPENING_INVENTORY.TRADE_NAME IS '企业名称';
COMMENT ON COLUMN OPENING_INVENTORY.CREDIT_CODE IS '企业信用代码';
COMMENT ON COLUMN OPENING_INVENTORY.OPT_DATE IS '统计日期';
COMMENT ON COLUMN OPENING_INVENTORY.CREATE_TIME IS '创建时间';


-- ----------------------------
-- Indexes structure for table OPENING_INVENTORY
-- ----------------------------

-- ----------------------------
-- Checks structure for table OPENING_INVENTORY
-- ----------------------------
ALTER TABLE OPENING_INVENTORY ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_FILE
-- ----------------------------
ALTER TABLE OPENING_INVENTORY ADD PRIMARY KEY (ID);