CREATE TABLE BD_RISK_DISPLAY_TAX (
ID NUMBER(20) NOT NULL ,
IE_FLAG VARCHAR2(64 CHAR) NOT NULL ,
DATETIME DATE NULL,
TAX NUMBER(20,5) NULL,
CHECK_TIME DATE NOT NULL,
ISCURRENT NUMBER(10) NOT NULL,
LASTUPDATE DATE NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_DISPLAY_TAX.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_DISPLAY_TAX.IE_FLAG IS '进出口标志';
COMMENT ON COLUMN BD_RISK_DISPLAY_TAX.DATETIME IS '统计日期';
COMMENT ON COLUMN BD_RISK_DISPLAY_TAX.CHECK_TIME IS '运行时间';
COMMENT ON COLUMN BD_RISK_DISPLAY_TAX.ISCURRENT IS '是否使用';
COMMENT ON COLUMN BD_RISK_DISPLAY_TAX.LASTUPDATE IS '数据最后更新时间';


-- ----------------------------
-- Indexes structure for table BD_RISK_DISPLAY_JINGYU
-- ----------------------------

-- ----------------------------
-- Checks structure for table BD_RISK_DISPLAY_JINGYU
-- ----------------------------
ALTER TABLE BD_RISK_DISPLAY_TAX ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_FILE
-- ----------------------------
ALTER TABLE BD_RISK_DISPLAY_TAX ADD PRIMARY KEY (ID);