CREATE TABLE BD_RISK_DISPLAY_JINGYU (
ID NUMBER(20) NOT NULL ,
IE_FLAG VARCHAR2(64 CHAR) NOT NULL ,
DATETIME DATE NULL,
ENTRY_NUM NUMBER(20,5) NULL,
TRADE_NUM NUMBER(20,5) NULL,
MONEY NUMBER(20,5) NULL,
TYPE VARCHAR2(64 CHAR) NULL,
CHECK_TIME DATE NOT NULL,
ISCURRENT NUMBER(10) NOT NULL,
LASTUPDATE DATE NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_DISPLAY_JINGYU.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_DISPLAY_JINGYU.IE_FLAG IS '进出口标志';
COMMENT ON COLUMN BD_RISK_DISPLAY_JINGYU.DATETIME IS '统计日期';
COMMENT ON COLUMN BD_RISK_DISPLAY_JINGYU.TYPE IS '类型';
COMMENT ON COLUMN BD_RISK_DISPLAY_JINGYU.CHECK_TIME IS '运行时间';
COMMENT ON COLUMN BD_RISK_DISPLAY_JINGYU.ISCURRENT IS '是否使用';
COMMENT ON COLUMN BD_RISK_DISPLAY_JINGYU.LASTUPDATE IS '数据最后更新时间';


-- ----------------------------
-- Indexes structure for table BD_RISK_DISPLAY_JINGYU
-- ----------------------------

-- ----------------------------
-- Checks structure for table BD_RISK_DISPLAY_JINGYU
-- ----------------------------
ALTER TABLE BD_RISK_DISPLAY_JINGYU ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_FILE
-- ----------------------------
ALTER TABLE BD_RISK_DISPLAY_JINGYU ADD PRIMARY KEY (ID);