CREATE TABLE BD_RISK_DISPLAY_MAIN (
  "ID" NUMBER(19) VISIBLE NOT NULL ,
  "IE_FLAG" VARCHAR2(1000 CHAR) VISIBLE ,
  "DATETIME" DATE VISIBLE ,
  "ENTRY_NUM" NUMBER(38,10) VISIBLE ,
  "RMB" NUMBER(38,10) VISIBLE ,
  "TRADE_NUM" NUMBER(38,10) VISIBLE ,
  "TYPE" VARCHAR2(1000 CHAR) VISIBLE ,
  "CORP_NUM" NUMBER(38,10) VISIBLE ,
  "ISCURRENT" NUMBER(38,10) VISIBLE,
  "LASTUPDATE" DATE VISIBLE 
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_DISPLAY_MAIN.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_DISPLAY_MAIN.IE_FLAG IS '进出口标志';
COMMENT ON COLUMN BD_RISK_DISPLAY_MAIN.DATETIME IS '统计日期';
COMMENT ON COLUMN BD_RISK_DISPLAY_MAIN.ENTRY_NUM IS '报关单量';
COMMENT ON COLUMN BD_RISK_DISPLAY_MAIN.RMB IS '货值';
COMMENT ON COLUMN BD_RISK_DISPLAY_MAIN.TRADE_NUM IS '交易对象数';
COMMENT ON COLUMN BD_RISK_DISPLAY_MAIN.TYPE IS '数据来源';
COMMENT ON COLUMN BD_RISK_DISPLAY_MAIN.CORP_NUM IS '统计企业数';
COMMENT ON COLUMN BD_RISK_DISPLAY_MAIN.ISCURRENT IS '是否使用：1(使用)；0(不使用)';
COMMENT ON COLUMN BD_RISK_DISPLAY_MAIN.LASTUPDATE IS '数据最后更新时间';


-- ----------------------------
-- Indexes structure for table BD_RISK_DISPLAY_MAIN
-- ----------------------------

-- ----------------------------
-- Checks structure for table BD_RISK_DISPLAY_MAIN
-- ----------------------------
ALTER TABLE BD_RISK_DISPLAY_MAIN ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_FILE
-- ----------------------------
ALTER TABLE BD_RISK_DISPLAY_MAIN ADD PRIMARY KEY (ID);