grant select on BD_RISK_CROSS_TRADE_ASSESSMENT_DETAILS to DW_CUS_RC_OPER;
grant select on BD_RISK_CROSS_TRADE_DEAL_WITH_ASSESSMENT to DW_CUS_RC_OPER;
grant select on BD_RISK_CROSS_TRADE_RESULT_FUTURE_WAREHOUSE_ALARM to DW_CUS_RC_OPER;
grant select on BD_RISK_CROSS_TRADE_RESULT_FUTURE_WAREHOUSE_CLEAN to DW_CUS_RC_OPER;
grant select on BD_RISK_CROSS_TRADE_RESULT_ORIGIN_COUNTRY_DIFFER_ALARM to DW_CUS_RC_OPER;
grant select on BD_RISK_CROSS_TRADE_RESULT_ORIGIN_COUNTRY_DIFFER_CLEAN to DW_CUS_RC_OPER;
grant select on BD_RISK_CROSS_TRADE_RESULT_SUB_ACCOUNT_ALARM to DW_CUS_RC_OPER;
grant select on BD_RISK_CROSS_TRADE_SCORE to DW_CUS_RC_OPER;
grant select on BD_RISK_CROSS_TRADE_SCORE_CM to DW_CUS_RC_OPER;
grant select on BD_RISK_CROSS_TRADE_SCORE_DTL to DW_CUS_RC_OPER;
grant select on BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN to DW_CUS_RC_OPER;
grant select on BD_RISK_CROSS_TRADE_RESULT_CHEMICAL_WARAING to DW_CUS_RC_OPER;
grant select on BD_RISK_CROSS_TRADE_RESULT_SUB_ACCOUNT_ALARM to DW_CUS_RC_OPER;
grant select on BD_RISK_WAREHOUSE_WEIGHT_CLEAN to DW_CUS_RC_OPER;
grant select on BD_RISK_RESULT_WAREHOUS_WARA to DW_CUS_RC_OPER;
grant SELECT on BD_RISK_CROSS_TRADE_RESULT_SUB_ACCOUNT_ALARM to DW_CUS_RC_OPER;
grant SELECT on BD_RISK_CROSS_TRADE_RESULT_SUB_ACCOUNT_CLEAN to DW_CUS_RC_OPER;
grant SELECT on BD_RISK_CROSS_TRADE_RESULT_SUB_ACCOUNT_DETAIL to DW_CUS_RC_OPER;
grant SELECT on BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN to DW_CUS_RC_OPER;
grant SELECT on BD_RISK_CROSS_TRADE_RESULT_CHEMICAL_WARAING to DW_CUS_RC_OPER;

-------------------------------------------------------------------------------
--海关中台赋权给用户
-------------------------------------------------------------------------------
grant SELECT on ENTRY_WORK_FLOW to DW_CUS_RC;
grant SELECT on ENTRY_HEAD to DW_CUS_RC;
grant SELECT on ENTRY_LIST to DW_CUS_RC;

grant SELECT on ENTRY_WORK_FLOW to n_epz_cus;
grant SELECT on ENTRY_HEAD to n_epz_cus;
grant SELECT on ENTRY_LIST to n_epz_cus;

grant SELECT on ODS_RISKH2000.COMPANY_REL to DW_CUS_RC;

