CREATE TABLE BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN (
ID NUMBER(20) NOT NULL,
BIZOP_ETPS_NM VARCHAR2(128 CHAR) NOT NULL,
WH_REC_PREENT_NO VARCHAR2(128 CHAR) NOT NULL,
BIZOP_ETPS_SCCD VARCHAR2(64 CHAR) NOT NULL,
BUSINESS_TYPECD VARCHAR2(64 CHAR) NOT NULL,
MASTER_CUSCD VARCHAR2(64 CHAR) NOT NULL,
INVT_IOCHKPT_STUCD VARCHAR2(64 CHAR) NOT NULL,
ACCESS_TIME DATE NOT NULL,
RLT_ENTRY_NO VARCHAR2(128 CHAR) NOT NULL,
ACCESS_TIME_DIFF NUMBER(10) NOT NULL,
CHECK_TIME DATE NOT NULL,
ISCURRENT NUMBER(10) NOT NULL,
LASTUPDATE DATE NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN.BIZOP_ETPS_NM IS '企业名称';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN.WH_REC_PREENT_NO IS '仓单编号';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN.BIZOP_ETPS_SCCD IS '经营企业18位信用代码';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN.BUSINESS_TYPECD IS '业务类型';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN.MASTER_CUSCD IS '主管海关代码';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN.INVT_IOCHKPT_STUCD IS 'INVT_IOCHKPT_STUCD';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN.ACCESS_TIME IS '报关单放行时间';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN.RLT_ENTRY_NO IS '关联报关单编号';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN.ACCESS_TIME_DIFF IS '统计时间与放行时间差';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN.CHECK_TIME IS '模型运行时间';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN.ISCURRENT IS '是否使用：1(使用)；0(不使用)';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN.LASTUPDATE IS '数据最后更新时间';


-- ----------------------------
-- Indexes structure for table BD_RISK_DETAIL_STOCK_ST1
-- ----------------------------

-- ----------------------------
-- Checks structure for table BD_RISK_DETAIL_STOCK_ST1
-- ----------------------------
ALTER TABLE BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_FILE
-- ----------------------------
ALTER TABLE BD_RISK_CROSS_TRADE_DETAIL_CHEMICAL_CLEAN ADD PRIMARY KEY (ID);