CREATE TABLE BD_RISK_CROSS_TRADE_ASSESSMENT_DETAILS (
ID NUMBER(20) NOT NULL ,
ORG_ID VARCHAR2(64 CHAR) NULL,
BUSINESS_TIME DATE NULL,
MIDDLE_RISK VARCHAR2(64 CHAR) NULL,
MIDDLE_RISK_RESOLVE VARCHAR2(64 CHAR) NULL,
HIGH_RISK VARCHAR2(64 CHAR) NULL,
HIGH_RISK_RESOLVE VARCHAR2(64 CHAR) NULL,
TYPE VARCHAR2(64 CHAR) NULL,
FUNCTION_TYPE VARCHAR2(64 CHAR) NULL,
BUSINESS VARCHAR2(64 CHAR) NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_CROSS_TRADE_ASSESSMENT_DETAILS.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_ASSESSMENT_DETAILS.ORG_ID IS '企业18位社会信用代码';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_ASSESSMENT_DETAILS.BUSINESS_TIME IS '业务时间';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_ASSESSMENT_DETAILS.MIDDLE_RISK IS '中风险';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_ASSESSMENT_DETAILS.MIDDLE_RISK_RESOLVE IS '中风险（已处置';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_ASSESSMENT_DETAILS.HIGH_RISK IS '高风险';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_ASSESSMENT_DETAILS.HIGH_RISK_RESOLVE IS '	高风险（已处置';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_ASSESSMENT_DETAILS.TYPE IS '类型';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_ASSESSMENT_DETAILS.FUNCTION_TYPE IS '功能层级';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_ASSESSMENT_DETAILS.BUSINESS IS '业务层级';

-- ----------------------------
-- Indexes structure for table BD_RISK_CROSS_TRADE_SCORE
-- ----------------------------

-- ----------------------------
-- Checks structure for table BD_RISK_CROSS_TRADE_SCORE
-- ----------------------------
ALTER TABLE BD_RISK_CROSS_TRADE_ASSESSMENT_DETAILS ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_FILE
-- ----------------------------
ALTER TABLE BD_RISK_CROSS_TRADE_ASSESSMENT_DETAILS ADD PRIMARY KEY (ID);

