CREATE TABLE BD_RISK_WORK_FLOW (
ENTRY_ID VARCHAR2(18 CHAR) NOT NULL ,
STEP_ID VARCHAR2(8 CHAR) NOT NULL,
CREATE_DATE DATE NOT NULL,
PROC_POS VARCHAR2(4 CHAR) NOT NULL,
STATUS_CODE VARCHAR2(32 CHAR) NOT NULL,
PROC_ER VARCHAR2(16 CHAR) NOT NULL,
PROC_RESULT VARCHAR2(8 CHAR) NOT NULL,
PREV_POS VARCHAR2(4 CHAR) NOT NULL,
PREV_ER VARCHAR2(8 CHAR) NOT NULL,
RECHK_MARK VARCHAR2(1 CHAR) NOT NULL,
RECHK_COMM VARCHAR2(255 CHAR) NOT NULL,
REC_CREATE_TIME DATE NOT NULL,
REC_LAST_UPDATE_TIME DATE NOT NULL,
REC_VERSION NUMBER(20) NOT NULL,
ARCH_VER VARCHAR2(32 CHAR) NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_WORK_FLOW.ENTRY_ID IS '报关单号';
COMMENT ON COLUMN BD_RISK_WORK_FLOW.STEP_ID IS '环节号码';
COMMENT ON COLUMN BD_RISK_WORK_FLOW.CREATE_DATE IS '处理日期';
COMMENT ON COLUMN BD_RISK_WORK_FLOW.PROC_POS IS '当前岗位代码';
COMMENT ON COLUMN BD_RISK_WORK_FLOW.STATUS_CODE IS '该岗位状态信息';
COMMENT ON COLUMN BD_RISK_WORK_FLOW.PROC_ER IS '当前处理人id';
COMMENT ON COLUMN BD_RISK_WORK_FLOW.PROC_RESULT IS '处理结果';
COMMENT ON COLUMN BD_RISK_WORK_FLOW.PREV_POS IS '下一岗位';
COMMENT ON COLUMN BD_RISK_WORK_FLOW.PREV_ER IS '处理人代码'
COMMENT ON COLUMN BD_RISK_WORK_FLOW.RECHK_MARK IS '审核备注标志';
COMMENT ON COLUMN BD_RISK_WORK_FLOW.RECHK_COMM IS '审核备注内容';
COMMENT ON COLUMN BD_RISK_WORK_FLOW.REC_CREATE_TIME IS '记录创建时间';
COMMENT ON COLUMN BD_RISK_WORK_FLOW.REC_LAST_UPDATE_TIME IS '最后更新时间';
COMMENT ON COLUMN BD_RISK_WORK_FLOW.REC_VERSION IS '数据版本号';
COMMENT ON COLUMN BD_RISK_WORK_FLOW.ARCH_VER IS '归档专用';