CREATE TABLE BD_RISK_WAREHOUSE_WEIGHT_CLEAN (
ID NUMBER(20) NOT NULL,
TRADE_NAME VARCHAR2(128 CHAR) NOT NULL,
CREDIT_CODE VARCHAR2(128 CHAR) NOT NULL,
ORG_ID VARCHAR2(64 CHAR) NOT NULL,
AREA NUMBER(10) NOT NULL,
AREA_USAGE VARCHAR2(64 CHAR) NOT NULL,
SUTTLE_TOTAL NUMBER(20) NOT NULL,
GROSS_WT_E NUMBER(20) NOT NULL,
GROSS_WT_I NUMBER(20) NOT NULL,
GROSS_WT_AVG NUMBER(20) NOT NULL,
BUSINESS_START_TIME DATE NOT NULL,
BUSINESS_END_TIME DATE NOT NULL,
MODEL_TIME DATE NOT NULL,
ISCURRENT NUMBER(10) NOT NULL,
LASTUPDATE DATE NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_WAREHOUSE_WEIGHT_CLEAN.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_WEIGHT_CLEAN.TRADE_NAME IS '企业名称';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_WEIGHT_CLEAN.CREDIT_CODE IS '经营企业18位信用代码';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_WEIGHT_CLEAN.ORG_ID IS '子账户ID';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_WEIGHT_CLEAN.AREA IS '仓库面积';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_WEIGHT_CLEAN.AREA_USAGE IS '仓库利用率';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_WEIGHT_CLEAN.SUTTLE_TOTAL IS '期末净重';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_WEIGHT_CLEAN.GROSS_WT_E IS '当期出口净重';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_WEIGHT_CLEAN.GROSS_WT_I IS '当期进口净重';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_WEIGHT_CLEAN.GROSS_WT_AVG IS '每平米重量';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_WEIGHT_CLEAN.BUSINESS_START_TIME IS '统计周期开始时间';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_WEIGHT_CLEAN.BUSINESS_END_TIME IS '统计周期结束时间';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_WEIGHT_CLEAN.MODEL_TIME IS '模型处理时间';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_WEIGHT_CLEAN.ISCURRENT IS '是否使用：1(使用)；0(不使用)';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_WEIGHT_CLEAN.LASTUPDATE IS '数据最后更新时间';


-- ----------------------------
-- Indexes structure for table BD_RISK_DETAIL_STOCK_ST1
-- ----------------------------

-- ----------------------------
-- Checks structure for table BD_RISK_DETAIL_STOCK_ST1
-- ----------------------------
ALTER TABLE BD_RISK_WAREHOUSE_WEIGHT_CLEAN ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_FILE
-- ----------------------------
ALTER TABLE BD_RISK_WAREHOUSE_WEIGHT_CLEAN ADD PRIMARY KEY (ID);