CREATE TABLE BD_RISK_CROSS_TRADE_SCORE (
ID NUMBER(20) NOT NULL ,
ORG_CODE VARCHAR2(64 CHAR) NOT NULL ,
HG_ORG_ID VARCHAR2(64 CHAR) NULL ,
ORG_TYPE VARCHAR2(64 CHAR) NULL ,
BUSINESS_TIME DATE NOT NULL ,
MODEL_CODE VARCHAR2(64 CHAR) NOT NULL ,
SCORE NUMBER(20,5) NOT NULL ,
ISCURRENT NUMBER(10) NOT NULL ,
LASTUPDATE DATE NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_CROSS_TRADE_SCORE.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_SCORE.ORG_CODE IS '企业18位社会信用代码';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_SCORE.HG_ORG_ID IS '海关企业代码';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_SCORE.ORG_TYPE IS '企业类型';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_SCORE.BUSINESS_TIME IS '统计时间';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_SCORE.MODEL_CODE IS '维度代码(为TOTAL时表示总分)';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_SCORE.SCORE IS '维度分数';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_SCORE.ISCURRENT IS '是否使用：1(使用)；0(不使用)';
COMMENT ON COLUMN BD_RISK_CROSS_TRADE_SCORE.LASTUPDATE IS '数据最后更新时间';


-- ----------------------------
-- Indexes structure for table BD_RISK_CROSS_TRADE_SCORE
-- ----------------------------

-- ----------------------------
-- Checks structure for table BD_RISK_CROSS_TRADE_SCORE
-- ----------------------------
ALTER TABLE BD_RISK_CROSS_TRADE_SCORE ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_FILE
-- ----------------------------
ALTER TABLE BD_RISK_CROSS_TRADE_SCORE ADD PRIMARY KEY (ID);
