
CREATE TABLE BD_RISK_DETAIL_SUPPLYCHAIN_SC1 (
    ID NUMBER(20) NOT NULL  ,
    TRADE_NAME VARCHAR2(256 CHAR) NOT NULL ,
    ORG_CODE VARCHAR2(256 CHAR) NOT NULL ,
    SC_COMPANY VARCHAR2(256 CHAR) NULL ,
    TRADE_TIMES NUMBER(10) NULL ,
    TRADE_VOLUMN NUMBER(20,5) NULL ,
    TYPE VARCHAR2(64 CHAR) NULL ,
    RATING VARCHAR2(64 CHAR) NULL ,
    BVD_RATE NUMBER(20,5) NULL,
    STAFF_NUM NUMBER(20,5) NULL,
    SHAREHOLDER_INCOME NUMBER(20,5) NULL,
    INCOME NUMBER(20,5) NULL,
    CHECK_TIME DATE NOT NULL ,
    ISCURRENT NUMBER(10) NOT NULL ,
    LASTUPDATE DATE NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_DETAIL_SUPPLYCHAIN_SC1.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_DETAIL_SUPPLYCHAIN_SC1.TRADE_NAME IS '经营企业';
COMMENT ON COLUMN BD_RISK_DETAIL_SUPPLYCHAIN_SC1.ORG_CODE  IS '经营企业信用代码';
COMMENT ON COLUMN BD_RISK_DETAIL_SUPPLYCHAIN_SC1.SC_COMPANY IS '供应链企业';
COMMENT ON COLUMN BD_RISK_DETAIL_SUPPLYCHAIN_SC1.TRADE_TIMES IS '交易次数';
COMMENT ON COLUMN BD_RISK_DETAIL_SUPPLYCHAIN_SC1.TRADE_VOLUMN IS '贸易额（rmb）';
COMMENT ON COLUMN BD_RISK_DETAIL_SUPPLYCHAIN_SC1.TYPE IS '供应链企业类型';
COMMENT ON COLUMN BD_RISK_DETAIL_SUPPLYCHAIN_SC1.RATING IS '破产指数';
COMMENT ON COLUMN BD_RISK_DETAIL_SUPPLYCHAIN_SC1.BVD_RATE IS 'BVD评级';
COMMENT ON COLUMN BD_RISK_DETAIL_SUPPLYCHAIN_SC1.STAFF_NUM IS '员工数量';
COMMENT ON COLUMN BD_RISK_DETAIL_SUPPLYCHAIN_SC1.SHAREHOLDER_INCOME IS '股东收入';
COMMENT ON COLUMN BD_RISK_DETAIL_SUPPLYCHAIN_SC1.INCOME IS '经营收入';
COMMENT ON COLUMN BD_RISK_DETAIL_SUPPLYCHAIN_SC1.CHECK_TIME IS '模型运行时间';
COMMENT ON COLUMN BD_RISK_DETAIL_SUPPLYCHAIN_SC1.ISCURRENT IS '是否使用：1(使用)；0(不使用)';
COMMENT ON COLUMN BD_RISK_DETAIL_SUPPLYCHAIN_SC1.LASTUPDATE IS '数据最后更新时间';

ALTER TABLE BD_RISK_DETAIL_SUPPLYCHAIN_SC1 ADD CHECK (ID IS NOT NULL);

ALTER TABLE BD_RISK_DETAIL_SUPPLYCHAIN_SC1 ADD PRIMARY KEY (ID);
