CREATE TABLE BD_RISK_WAREHOUSE_ORDER (
ID NUMBER(10) NOT NULL,
ORG_CODE VARCHAR2(128 CHAR) NOT NULL,
ORG_NAME VARCHAR2(128 CHAR) NOT NULL,
ORDER_NO VARCHAR2(128 CHAR) NOT NULL,
ORDER_TYPE VARCHAR2(64 CHAR) NOT NULL,
CUSTOMER_NAME VARCHAR2(128 CHAR),
CUSTOMER_COUNTRY VARCHAR2(128 CHAR),
COP_G_NO VARCHAR2(128 CHAR) NOT NULL,
G_NAME VARCHAR2(128 CHAR),
HS_CODE VARCHAR2(128 CHAR),
QTY_ORDER VARCHAR2(64 CHAR) NOT NULL,
UNIT_CO VARCHAR2(64 CHAR) NOT NULL,
QTY_1 VARCHAR2(64 CHAR),
UNIT_1 VARCHAR2(64 CHAR),
UNIT_PRICE VARCHAR2(64 CHAR),
TRADE_CURR VARCHAR2(64 CHAR),
EX_RATE VARCHAR2(64 CHAR),
ORDER_DATE DATE NOT NULL,
EST_DATE DATE,
COMPLETE_DATE DATE,
STATUS VARCHAR2(64 CHAR),
CAPXACTION VARCHAR2(64 CHAR) NOT NULL,
LASTUPDATEDDT DATE NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.ORG_CODE IS '企业信用代码';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.ORG_NAME IS '企业名称';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.ORDER_NO IS '客户订单编号';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.ORDER_TYPE IS '订单类型';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.CUSTOMER_NAME IS '客户名称';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.CUSTOMER_COUNTRY IS '客户所属国别';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.COP_G_NO IS '商品料号';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.G_NAME IS '商品名称';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.HS_CODE IS '商品编码';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.QTY_ORDER IS '商品数量';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.UNIT_CO IS '商品计量单位';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.QTY_1 IS '法定数量';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.UNIT_1 IS '法定单位';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.UNIT_PRICE IS '商品单价';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.TRADE_CURR IS '币制';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.EX_RATE IS '汇率';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.ORDER_DATE IS '下单时间';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.EST_DATE IS '订单预期完成时间';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.COMPLETE_DATE IS '订单实际完成时间';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.STATUS IS '订单是否完成';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.CAPXACTION IS '增删改类型';
COMMENT ON COLUMN BD_RISK_WAREHOUSE_ORDER.LASTUPDATEDDT IS '最后更新时间';


ALTER TABLE BD_RISK_WAREHOUSE_ORDER ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table BD_RISK_WAREHOUSE_ORDER
-- ----------------------------
ALTER TABLE BD_RISK_WAREHOUSE_ORDER ADD PRIMARY KEY (ID);