CREATE TABLE BD_RISK_DETAIL_WAREHOUSE_WH1_C (
ID NUMBER(20) NOT NULL ,
ORG_CODE VARCHAR2(64 CHAR) NOT NULL ,
I_E_MARK VARCHAR2(16 CHAR) NOT NULL ,
CUSTOMS_CODE VARCHAR2(32 CHAR) NULL ,
I_E_PORT VARCHAR2(32 CHAR) NULL,
I_E_DATE DATE NULL,
FIRST_DECL_TIME DATE NULL,
TRAF_MODE VARCHAR2(16 CHAR) NULL,
GOODS_OWNER VARCHAR2(64 CHAR) NULL,
ENTRY_NO VARCHAR2(64 CHAR) NOT NULL,
GOODS_NO NUMBER(20) NOT NULL,
GOODS_CODE VARCHAR2(64 CHAR) NULL,
GOODS_NAME VARCHAR2(64 CHAR) NULL,
GOODS_MODEL VARCHAR2(512 CHAR) NULL,
ORG_CODE_CY VARCHAR2(64 CHAR) NULL,
G_QTY NUMBER(20,5) NULL,
G_UNIT VARCHAR2(32 CHAR) NULL,
QTY_1 NUMBER(20,5) NULL,
UNIT_1 VARCHAR2(32 CHAR) NULL,
QTY_2 NUMBER(20,5) NULL,
UNIT_2 VARCHAR2(32 CHAR) NULL,
TRADE_CURR_CODE VARCHAR2(32 CHAR) NULL,
DECL_TOTAL NUMBER(20,5) NULL,
SRC VARCHAR2(32 CHAR) NULL,
CHECK_TIME DATE NOT NULL,
ISCURRENT NUMBER(10) NOT NULL,
LASTUPDATE DATE NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.ORG_CODE IS '公司社会信用代码';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.I_E_MARK IS '进出口标记';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.CUSTOMS_CODE IS '海关关区代码';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.I_E_PORT IS '进出口岸';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.I_E_DATE IS '进出口日期';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.FIRST_DECL_TIME IS '首个海关回执时间';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.TRAF_MODE IS '运输方式';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.GOODS_OWNER IS '货主名称';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.ENTRY_NO IS '报关单号';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.GOODS_NO IS '报关单中货物序号';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.GOODS_CODE IS 'HSCODE';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.GOODS_NAME IS '货物品名';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.GOODS_MODEL IS '货物型号';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.ORG_CODE_CY IS '原产国代码';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.G_QTY IS '货物数量';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.G_UNIT IS '货物单位代码';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.QTY_1 IS '第一货物数量';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.UNIT_1 IS '第一货物单位代码';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.QTY_2 IS '第二货物数量';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.UNIT_2 IS '第二货物单位代码';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.TRADE_CURR_CODE IS '币制代码';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.DECL_TOTAL IS '申报总价';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.SRC IS '数据来源';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.CHECK_TIME IS '运行时间';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.ISCURRENT IS '是否使用';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_C.LASTUPDATE IS '数据最后更新时间';


-- ----------------------------
-- Indexes structure for table BD_RISK_DETAIL_WAREHOUSE_WH1_C
-- ----------------------------

-- ----------------------------
-- Checks structure for table BD_RISK_DETAIL_WAREHOUSE_WH1_C
-- ----------------------------
ALTER TABLE BD_RISK_DETAIL_WAREHOUSE_WH1_C ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_FILE
-- ----------------------------
ALTER TABLE BD_RISK_DETAIL_WAREHOUSE_WH1_C ADD PRIMARY KEY (ID);