CREATE TABLE BD_RISK_DETAIL_WAREHOUSE_WH1_S (
ID NUMBER(20) NOT NULL ,
ORG_CODE VARCHAR2(64 CHAR) NOT NULL ,
CUSTOMS_CODE VARCHAR2(32 CHAR) NULL ,
STOCK_BILL_TYPE VARCHAR2(32 CHAR) NULL ,
STOCK_TYPE VARCHAR2(32 CHAR) NULL ,
BILL_TYPE VARCHAR2(32 CHAR) NULL ,
BUSINESS_TYPE VARCHAR2(32 CHAR) NULL ,
BILL_STATUS VARCHAR2(32 CHAR) NULL ,
CLASSIFY_TYPE VARCHAR2(32 CHAR) NULL ,
SUPV_MODE VARCHAR2(32 CHAR) NULL ,
I_E_PORT VARCHAR2(32 CHAR) NULL,
TRAF_MODE VARCHAR2(16 CHAR) NULL,
ENTRY_NO VARCHAR2(64 CHAR) NOT NULL,
ENTRY_GDS_SEQNO NUMBER(20) NOT NULL,
HS_CODE VARCHAR2(64 CHAR) NULL,
G_NAME VARCHAR2(64 CHAR) NULL,
G_MODEL VARCHAR2(512 CHAR) NULL,
ORIGIN_COUNTRY_CODE VARCHAR2(64 CHAR) NULL,
QTY NUMBER(20,5) NULL,
G_UNIT VARCHAR2(32 CHAR) NULL,
QTY_1 NUMBER(20,5) NULL,
UNIT_1 VARCHAR2(32 CHAR) NULL,
QTY_2 NUMBER(20,5) NULL,
UNIT_2 VARCHAR2(32 CHAR) NULL,
TRADE_CURR VARCHAR2(32 CHAR) NULL,
TRADE_TOTAL NUMBER(20,5) NULL,
STARTDT DATE NULL,
CHECK_TIME DATE NOT NULL,
ISCURRENT NUMBER(10) NOT NULL,
LASTUPDATE DATE NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.ORG_CODE IS '公司社会信用代码';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.CUSTOMS_CODE IS '海关关区代码';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.STOCK_BILL_TYPE IS '出入库单进出类型';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.STOCK_TYPE IS '库存类型';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.BILL_TYPE IS '出入库类型';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.BUSINESS_TYPE IS '业务类别';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.BILL_STATUS IS '当前记录出入库状态';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.CLASSIFY_TYPE IS '料件成品标志';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.SUPV_MODE IS '监管方式';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.I_E_PORT IS '进出口岸';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.TRAF_MODE IS '运输方式';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.ENTRY_NO IS '报关单号';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.ENTRY_GDS_SEQNO IS '报关单中货物序号';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.HS_CODE IS 'HSCODE';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.G_NAME IS '货物品名';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.G_MODEL IS '货物型号';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.ORIGIN_COUNTRY_CODE IS '原产国代码';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.QTY IS '货物数量';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.G_UNIT IS '货物单位代码';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.QTY_1 IS '第一货物数量';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.UNIT_1 IS '第一货物单位代码';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.QTY_2 IS '第二货物数量';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.UNIT_2 IS '第二货物单位代码';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.TRADE_CURR IS '币制代码';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.TRADE_TOTAL IS '总价';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.STARTDT IS '开始时间';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.CHECK_TIME IS '运行时间';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.ISCURRENT IS '是否使用';
COMMENT ON COLUMN BD_RISK_DETAIL_WAREHOUSE_WH1_S.LASTUPDATE IS '数据最后更新时间';


-- ----------------------------
-- Indexes structure for table BD_RISK_DETAIL_WAREHOUSE_WH1_S
-- ----------------------------

-- ----------------------------
-- Checks structure for table BD_RISK_DETAIL_WAREHOUSE_WH1_S
-- ----------------------------
ALTER TABLE BD_RISK_DETAIL_WAREHOUSE_WH1_S ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table UPLOAD_FILE
-- ----------------------------
ALTER TABLE BD_RISK_DETAIL_WAREHOUSE_WH1_S ADD PRIMARY KEY (ID);