CREATE TABLE BD_RISK_GAODE_GPS (
ID NUMBER(20) NULL,
CAR_NO VARCHAR2(64) NULL ,
X_PARAM NUMBER(20,7) NULL,
Y_PARAM NUMBER(20,7) NULL,
DURATION NUMBER(10) NULL,
ISCURRENT NUMBER(1) NULL,
LASTUPDATE DATE NULL
)
;
