CREATE TABLE BD_RISK_TRACK_INFO (
ID NUMBER(20) NULL,
UNF_SC_ID VARCHAR2(64) NULL ,
DOCU_TYPE VARCHAR2(200),
DOCU_CODE VARCHAR2(80),
CTNR_LORRY_LPN VARCHAR2(64) NULL ,
VEHICLE_DEPT_DATE DATE NULL,
VEHICLE_ARRIVAL_DATE DATE NULL,
VEHICLE_DEPT_PLACE_LON VARCHAR2(128) NULL,
VEHICLE_DEPT_PLACE_LAT VARCHAR2(128) NULL,
VEHICLE_ARRIVAL_PLACE_LON VARCHAR2(128) NULL,
VEHICLE_ARRIVAL_PLACE_LAT VARCHAR2(128) NULL,
validated_flag NUMBER(1) default 0,
ISCURRENT NUMBER(1) NULL,
LASTUPDATEDDT timestamp(6) NULL
)
;

COMMENT ON COLUMN BD_RISK_TRACK_INFO.ID IS 'ID';
COMMENT ON COLUMN BD_RISK_TRACK_INFO.UNF_SC_ID IS '统一社会信用代码';
COMMENT ON COLUMN BD_RISK_TRACK_INFO.DOCU_TYPE IS '单证类型';
COMMENT ON COLUMN BD_RISK_TRACK_INFO.DOCU_CODE IS '单证代码';
COMMENT ON COLUMN BD_RISK_TRACK_INFO.CTNR_LORRY_LPN IS '集卡车牌号';
COMMENT ON COLUMN BD_RISK_TRACK_INFO.VEHICLE_DEPT_DATE IS '出发时间';
COMMENT ON COLUMN BD_RISK_TRACK_INFO.VEHICLE_ARRIVAL_DATE IS '到达时间';
COMMENT ON COLUMN BD_RISK_TRACK_INFO.VEHICLE_DEPT_PLACE_LON IS '车辆出发地点经度';
COMMENT ON COLUMN BD_RISK_TRACK_INFO.VEHICLE_DEPT_PLACE_LAT IS '车辆出发地点纬度';
COMMENT ON COLUMN BD_RISK_TRACK_INFO.VEHICLE_ARRIVAL_PLACE_LON IS '车辆到达地点经度';
COMMENT ON COLUMN BD_RISK_TRACK_INFO.VEHICLE_ARRIVAL_PLACE_LAT IS '车辆到达地点纬度';
COMMENT ON COLUMN BD_RISK_TRACK_INFO.validated_flag IS '验证标记；1：已验证；2：未验证';
COMMENT ON COLUMN BD_RISK_TRACK_INFO.ISCURRENT IS '是否使用';
COMMENT ON COLUMN BD_RISK_TRACK_INFO.LASTUPDATEDDT IS '数据最后更新时间';